### ISSUE TITLE
bad argument #1 to 'space' (string expected, got nil)

### ISSUE THREAD

**Issue by atropos112** [sontungexpt/better-diagnostic-virtual-text#1]
I have spent some time trying to understand what is causing an error message to pop up, I am still not sure what is causing it (seems somewhat random at times), having ran out of other options, I figured I'll make an issue maybe its something that isn't my setup related but a real bug. I get the following error message:

```
Error executing lua callback: ...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:734: bad argument #1 to 'space' (string expected, got nil)
stack traceback:
	[C]: in function 'space'
	...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:734: in function 'format_line_chunks'
	...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:855: in function 'generate_virtual_texts'
	...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:982: in function 'show_diagnostic'
	...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:1100: in function 'show_diagnostic'
	...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:1272: in function <...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:1249>
```

My lazy config is 
```lua
	{
		"sontungexpt/better-diagnostic-virtual-text",
		event = "LspAttach",
		opts = {
			inline = false,
			ui = {
				above = true,
			},
		},
	},
```
and i attach it in my `on_attach` function (within lsp setup part) with 
```lua
	require("better-diagnostic-virtual-text.api").setup_buf(bufnr, nil)
	local lsp = vim.lsp
	lsp.handlers["textDocument/signatureHelp"] = lsp.with(lsp.handlers.signature_help, {
		border = "single",
		focusable = false,
		relative = "cursor",
	})
	lsp.handlers["textDocument/hover"] = lsp.with(lsp.handlers.hover, { border = "single" })
...
```
at the top of my `on_attach` function. I noticed this happens in more than one language (at least in python, lua and nix) so unlikely to be specific lang or lua LSP dependent (although there is a copilot and null-ls LSPs with me in all 3 of these, so these may have some weird interactions). My nvim version is v0.10.0. 

I suspect adding 
```lua
	if not num then
		return ""
	end
```
at the top of the space function will solve the issue ,but am not sure if this is the way to go or a "quick and dirty" solution.

**Comment by sontungexpt** [comment]
I have never encountered this error before, however I see your config has a bit of a mistake. You only need to configure one of two ways: add options to the lazy config or you just need to download the plugin and call setup_compensation in on_attach if only If you call both, it will duplicate the event and maybe that's the reason. 
Try this
```lua
{
	"sontungexpt/better-diagnostic-virtual-text",
	lazy = true,
},
```
and add 
```lua
require("better-diagnostic-virtual-text.api").setup_buf(bufnr, nil) 
```
to your on_attach function for each client. If each still happens please tell me

**Comment by atropos112** [comment]
Still seeing

```
Error executing lua callback: ...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:738: bad argument #1 to 'space' (string expected, got nil)
stack traceback:
	[C]: in function 'space'
	...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:738: in function 'format_line_chunks'
	...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:859: in function 'generate_virtual_texts'
	...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:986: in function 'show_diagnostic'
	...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:1104: in function 'show_diagnostic'
	...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:1276: in function <...-virtual-text/lua/better-diagnostic-virtual-text/api.lua:1253>
```
this is after having 

```lua
	{
		"sontungexpt/better-diagnostic-virtual-text",
		lazy = true,
	},
```
in my lazy plugins (can be seen here https://github.com/atropos112/nvim/blob/main/lua/atro/plugins/lsp.lua#L66) and in my on_attach i now have 

```lua
	require("better-diagnostic-virtual-text.api").setup_buf(bufnr, {
		inline = false,
		ui = {
			above = true,
		},
	})
```
as can be seen here
https://github.com/atropos112/nvim/blob/main/lua/atro/utils/lsp.lua#L8

and yet still seeing the issues :(

**Comment by sontungexpt** [comment]
Can you explain more clearly when it usually happens when the message is very long or short

**Comment by sontungexpt** [comment]
I think I understand why there is some logic error when window is larger than 160 columns. I fixed it, try again.

**Comment by sontungexpt** [comment]
my screen is small so i have never met it, sorry about that.

**Comment by atropos112** [comment]
Having used it for few hours im pretty sure the issue is resolved, thank you a lot!!

**Comment by sontungexpt** [comment]
Thanks for letting me know the error
