### ISSUE TITLE
Go/Gopls support

### ISSUE THREAD

**Issue by lvim-tech** [sontungexpt/better-diagnostic-virtual-text#2]
Thanks for amazing plugin!!!
I think the plugin doesn't work properly with go files. Errors are not displayed.
Thanks in advance!

**Comment by sontungexpt** [comment]
what did you use, go.nvim or just gopls

**Comment by sontungexpt** [comment]
did you use go.nvim or just golps
![image](https://github.com/user-attachments/assets/e3b3f32c-2785-4bbb-ac6b-aa4071c65ea5)
it works for me

**Comment by lvim-tech** [comment]
just gopls

![Screenshot from 2024-08-09 15-31-13](https://github.com/user-attachments/assets/b6fd3bb0-8b56-440b-a133-16b049a86567)
![Screenshot from 2024-08-09 15-33-16](https://github.com/user-attachments/assets/ecec13e1-982b-41d9-bf43-798d5e639104)

**Comment by sontungexpt** [comment]
> just gopls
> 
> ![Screenshot from 2024-08-09 15-31-13](https://github.com/user-attachments/assets/b6fd3bb0-8b56-440b-a133-16b049a86567)
> ![Screenshot from 2024-08-09 15-33-16](https://github.com/user-attachments/assets/ecec13e1-982b-41d9-bf43-798d5e639104)
> 

Can you give me more details about it, i have't used go before so if had more info, i can debug it easier

**Comment by lvim-tech** [comment]
https://go.dev/doc/tutorial/getting-started

**Comment by sontungexpt** [comment]
> https://go.dev/doc/tutorial/getting-started

Can you give me your test file content

**Comment by lvim-tech** [comment]
Just try this
```
package main

import "fmt"

func main() {
	sdf
	fmt.Println("Hello, World!")
}
```
![Screenshot from 2024-08-09 16-47-42](https://github.com/user-attachments/assets/80fce80a-be3f-4f86-aed5-26fa99ed3bbe)

**Comment by lvim-tech** [comment]
another bug - the virtual text is on inlay-hints
![Screenshot from 2024-08-09 17-24-42](https://github.com/user-attachments/assets/dd63549b-0c1b-4af8-a8ba-da905d461860)
![Screenshot from 2024-08-09 17-25-28](https://github.com/user-attachments/assets/8e3b42c5-ff47-48ce-8784-1525dd447dd0)
